name: Actions workflow

on:
  push:
    branches:
      - "master"
  
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout action
        uses: actions/checkout@v3
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"